spring.datasource.url=jdbc:mysql://localhost:3306/dentaloffice
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.security.user.name=admin
#spring.security.user.password=admin

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=andreeastingu26@gmail.com
spring.mail.password=cckw jxop wcti yurc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true